### ISSUE TITLE
roflcoptor doesn't notice when it fails to bind a listener

### ISSUE THREAD

**Issue by leif** [subgraph/roflcoptor#30]
I ran roflcoptor while tor was still listening on 9051. roflcoptor logged this:

```
14:29:06 ▶ NOTI 00d unauthenticated listener starting on tcp:127.0.0.1:9051
```

but it is not actually listening there, because tor still is.

**Comment by david415** [comment]
fixed in https://github.com/subgraph/procsnitchd/commit/ec8a9fbed5630ce64fc59c145ff51ecbb2a4efc3
