### ISSUE TITLE
package for subgraph OS

### ISSUE THREAD

**Issue by dma** [subgraph/roflcoptor#38]

**Comment by david415** [comment]
should the unit file use mkdir -p? it would mean less noisy output to the log.
https://github.com/david415/roflcoptor/commit/8b9281d994b1e31f60eb8a4101a8091434b7b6ab

**Comment by adrelanos** [comment]
No. That is systemd-tmpfiles for. Example:
- https://github.com/Whonix/sdwdate/blob/master/usr/lib/tmpfiles.d/sdwdate.conf
- and perhaps https://github.com/Whonix/sdwdate/blob/11bad33cf1d40472754f7c4478e07f3aa6908d32/debian/sdwdate.postinst#L53-L60

**Comment by dma** [comment]
You're right, this is clearly the proper systemd way to do it. We will fix it.
