### ISSUE TITLE
Add "name" attribute to filter policy definition; include it when Roflcoptor logs events

### ISSUE THREAD

**Issue by dma** [subgraph/roflcoptor#58]
Roflcoptor filter policies need a name attribute for recording events to logs. Currently Roflcoptor records entries using ExePath, but this does not make sense for Oz as the "ExePath" is the same for all sandboxed apps. 

In session.go:

```
log.Errorf("filter policy for %s DENY: %s A<-T: [%q]\n", s.policy.ExecPath, 
appName, responseStr)
```

The above results in log entries for events that cannot be distinguished among the Oz applications using Roflcoptor:

```
Sep 27 17:50:50 subgraph roflcoptor[25602]: ERRO 6ad filter policy 
for /usr/sbin/oz-daemon DENY: 
[/usr/sbin/oz-daemon] A<-T: ["650 STATUS_CLIENT NOTICE 
CIRCUIT_NOT_ESTABLISHED REASON=CLOCK_JUMPED"]
```

Policies should include a field that has an arbitrary value that exist for the purpose of identifying the listener to which the policy was attached when creating log entries.

**Comment by david415** [comment]
my latest dev branch has got this feature addition; added Name field to policies. Name gets printed as appName in log messages. Works great with Oz apps. Need code review:
https://github.com/subgraph/roflcoptor/pull/60

i think when we merge that PR we can close this ticket.
