### ISSUE TITLE
Support for unix socket public control port

### ISSUE THREAD

**Issue by xSmurf** [subgraph/roflcoptor#9]
More and more applications are moving to unix socket control port all together, we should support using one as the listener. Possibly, as tor does, support for doing both a control port and a control unix socket.

**Comment by david415** [comment]
we need go-procsnitch to support this feature. here's the ticket https://github.com/subgraph/go-procsnitch/issues/3

**Comment by david415** [comment]
this dev branch uses my go-procsnitch dev branch to implement unix domain socket support
https://github.com/david415/roflcoptor/tree/1.add_unix_domain_socket.1

although it doesn't work because the acquired proc info is for the server not the client... maybe i did something wrong.

**Comment by david415** [comment]
ok my dev branch now works due to the changes i made to go-procsnitch... this means you must you my dev branch of go-procsnitch in order for this roflcoptor dev branch to work.

please review.

**Comment by david415** [comment]
@NOTE that this dev branch is based on my other dev branch from https://github.com/subgraph/roflcoptor/issues/13

**Comment by david415** [comment]
here's my latest dev branch
https://github.com/david415/roflcoptor/tree/1.add_unix_domain_socket.2

**Comment by david415** [comment]
ok we can now make a very small change to roflcoptor as soon as the unix domain socket changes are merged into go-procsnitch master branch.

**Comment by david415** [comment]
fixed here:
https://github.com/subgraph/roflcoptor/commit/0916db26d0b6a202a01da8c45a8deb9a7c88e7d2
